### PR TITLE
fix!: import `defineConfig` from `kirbyup/config` (#19)

### LINKED ISSUE #19: Extremely slow starts if kirbyup.config exists
When there's a `kirbyup.config.(js|mjs|...)` in a project, kirbyup takes roughly 20x as long to start building (or with #18: serving) the plugin.

Without a kirbyup config, my plugin build finishes in `~0.7s`. If a kirbyup config exists, it takes `~14s`, almost all of which is the loading of the config. I added a `console.log` to my config file – nothing happens for ages, then the config executes and is logged and shortly after the build completes.

I guess `unconfig` takes long to check all possible config paths and then compile the found config? But no matter the cause, not a great experience :(

### PR DESCRIPTION
**Pull request by johannschopplich**
Fix #19.

@jonaskuske What do you think? Seems like the most straight forward solution.

### CODE REVIEW

**Comment by jonaskuske** [comment]
Would've said it looks good, but now that I've tested it, it doesn't appear to work :(

TS / IntelliSense doesn't pick up on the export, there's no auto-complete and auto-import for `defineConfig` and if you import it manually it still doesn't offer type completion. 🤔

**Comment by johannschopplich** [comment]
Node.js v12+ extends [package entry points features](https://nodejs.org/api/packages.html#packages_package_entry_points) like [subpath exports](https://nodejs.org/api/packages.html#packages_subpath_exports) or [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports), but TypeScript supports them only with the `NodeNext` module resolution:

```json
{
  "compilerOptions": {
    "moduleResolution": "NodeNext"
  }
}

```

Reference: https://github.com/microsoft/TypeScript/issues/33079

Because many developers, including myself, are using `"moduleResolution": "Node"` solely, we add a workaround utilizing `typesVersions`.

**Comment by jonaskuske** [comment]
Found the culprit!

The downstream project needs to add a `jsconfig.json` / `tsconfig.json` with

```json5
{
  "compilerOptions": {
    "moduleResolution": "Node16"
  }
}
```

so TypeScript/IntelliSense correctly resolves `package.json#exports`.

With that, suggestions work if you try to import the function and the typings work too.

Auto-import still doesn't work, so you can't just type `defineC`, hit Tab and VSCode completes the function name and adds the import to the top automatically, but that's just a minor issue.

**Comment by jonaskuske** [comment]
Update: the workaround is working!

Still not for auto-imports, but that might just be a TS/IntelliSense bug or limitation?

**Comment by johannschopplich** [comment]
Limitation of the types version workaround. Still, everything we can do for the upstream project.

**Comment by jonaskuske** [comment]
> Limitation of the types version workaround

Are you sure? I see the same behavior with `"moduleResolution": "Node16"` and without the `typesVersion` workaround, so maybe it's a broader bug with type indexing/acquisition in ESM modules?

**Comment by johannschopplich** [comment]
Good question, I don't know. 👀

**Pull request merged**
